# Movie Recommendation System

---


**Recommender System** is a system that seeks to predict or filter preferences according to the user’s choices. Recommender systems are utilized in a variety of areas including movies, music, news, books, research articles, search queries, social tags, and products in general. Recommender systems produce a list of recommendations in any of the two ways –
> 1. **Collaborative filtering:** Collaborative filtering approaches build a model from the user’s past behavior (i.e. items purchased or searched by the user) as well as similar decisions made by other users. This model is then used to predict items (or ratings for items) that users may have an interest in.

> 2. **Content-based filtering:** Content-based filtering approaches uses a series of discrete characteristics of an item in order to recommend additional items with similar properties. Content-based filtering methods are totally based on a description of the item and a profile of the user’s preferences. It recommends items based on the user’s past preferences.


This project is based on Content-based filtering

Let’s develop a basic recommendation system using Python and Pandas. Let’s focus on providing a basic recommendation system by suggesting items that are most similar to a particular item, in this case, movies. It just tells what movies/items are most similar to the user’s movie choice.

# **Import Library**

In [ ]:
import pandas as pd
import numpy as np

# **Import Dataset**

In [ ]:
movies = pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Movies%20Recommendation.csv')

In [ ]:
movies.head(32)

Movie_ID                                        Movie_Title  \
0          1                                         Four Rooms   
1          2                                          Star Wars   
2          3                                       Finding Nemo   
3          4                                       Forrest Gump   
4          5                                    American Beauty   
5          6                                 Dancer in the Dark   
6          7                                  The Fifth Element   
7          8                                         Metropolis   
8          9                                 My Life Without Me   
9         10  Pirates of the Caribbean: The Curse of the Bla...   
10        11                                  Kill Bill: Vol. 1   
11        12                                            Jarhead   
12        13                                     Apocalypse Now   
13        14                                         Unforgiven   
14        15                                 The Simpsons Movie   
15        16              Eternal Sunshine of the Spotless Mind   
16        17                                      Amores perros   
17        18         Pirates of the Caribbean: Dead Man's Chest   
18        19                              A History of Violence   
19        20                              2001: A Space Odyssey   
20        21                                             8 Mile   
21        22                                     Absolute Power   
22        23                                             Brazil   
23        24                                      Walk the Line   
24        25                                Million Dollar Baby   
25        26                                       Billy Elliot   
26        27                                 American History X   
27        28                                  War of the Worlds   
28        29                                      Mars Attacks!   
29        30                                     Before Sunrise   
30        31                                            Memento   
31        32                                       Blade Runner   

                                          Movie_Genre Movie_Language  \
0                                        Crime Comedy             en   
1                    Adventure Action Science Fiction             en   
2                                    Animation Family             en   
3                                Comedy Drama Romance             en   
4                                               Drama             en   
5                                   Drama Crime Music             en   
6   Adventure Fantasy Action Thriller Science Fiction             en   
7                               Drama Science Fiction             de   
8                                       Drama Romance             en   
9                            Adventure Fantasy Action             en   
10                                       Action Crime             en   
11                                          Drama War             en   
12                                          Drama War             en   
13                                            Western             en   
14                            Animation Comedy Family             en   
15                      Science Fiction Drama Romance             en   
16                                     Drama Thriller             es   
17                           Adventure Fantasy Action             en   
18                               Drama Thriller Crime             en   
19                  Science Fiction Mystery Adventure             en   
20                                              Drama             en   
21                               Crime Drama Thriller             en   
22                             Comedy Science Fiction             en   
23                                Drama Music Romance           

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4760 entries, 0 to 4759
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Movie_ID                  4760 non-null   int64  
 1   Movie_Title               4760 non-null   object 
 2   Movie_Genre               4760 non-null   object 
 3   Movie_Language            4760 non-null   object 
 4   Movie_Budget              4760 non-null   int64  
 5   Movie_Popularity          4760 non-null   float64
 6   Movie_Release_Date        4760 non-null   object 
 7   Movie_Revenue             4760 non-null   int64  
 8   Movie_Runtime             4758 non-null   float64
 9   Movie_Vote                4760 non-null   float64
 10  Movie_Vote_Count          4760 non-null   int64  
 11  Movie_Homepage            1699 non-null   object 
 12  Movie_Keywords            4373 non-null   object 
 13  Movie_Overview            4757 non-null   object 
 14  Movie_Pr

In [ ]:
movies.describe()

Movie_ID  Movie_Budget  Movie_Popularity  Movie_Revenue  \
count  4760.000000  4.760000e+03       4760.000000   4.760000e+03   
mean   2382.566387  2.920129e+07         21.599510   8.263743e+07   
std    1377.270159  4.075620e+07         31.887919   1.630554e+08   
min       1.000000  0.000000e+00          0.000372   0.000000e+00   
25%    1190.750000  9.257500e+05          4.807074   0.000000e+00   
50%    2380.500000  1.500000e+07         13.119058   1.944716e+07   
75%    3572.250000  4.000000e+07         28.411929   9.341276e+07   
max    4788.000000  3.800000e+08        875.581305   2.787965e+09   

       Movie_Runtime   Movie_Vote  Movie_Vote_Count  
count    4758.000000  4760.000000       4760.000000  
mean      107.184111     6.113866        692.508403  
std        21.960332     1.141294       1235.007337  
min         0.000000     0.000000          0.000000  
25%        94.000000     5.600000         55.000000  
50%       104.000000     6.200000        238.000000  
75%       118.000000     6.800000        740.250000  
max       338.000000    10.000000      13752.000000

In [ ]:
movies.isnull().sum()

Movie_ID                       0
Movie_Title                    0
Movie_Genre                    0
Movie_Language                 0
Movie_Budget                   0
Movie_Popularity               0
Movie_Release_Date             0
Movie_Revenue                  0
Movie_Runtime                  2
Movie_Vote                     0
Movie_Vote_Count               0
Movie_Homepage              3061
Movie_Keywords               387
Movie_Overview                 3
Movie_Production_House         0
Movie_Production_Country       0
Movie_Spoken_Language          0
Movie_Tagline                818
Movie_Cast                    27
Movie_Crew                     0
Movie_Director                22
dtype: int64

In [ ]:
movies.shape

(4760, 21)

In [ ]:
movies.columns

Index(['Movie_ID', 'Movie_Title', 'Movie_Genre', 'Movie_Language',
       'Movie_Budget', 'Movie_Popularity', 'Movie_Release_Date',
       'Movie_Revenue', 'Movie_Runtime', 'Movie_Vote', 'Movie_Vote_Count',
       'Movie_Homepage', 'Movie_Keywords', 'Movie_Overview',
       'Movie_Production_House', 'Movie_Production_Country',
       'Movie_Spoken_Language', 'Movie_Tagline', 'Movie_Cast', 'Movie_Crew',
       'Movie_Director'],
      dtype='object')

# **Get Feature Selection**


In [ ]:
movies_features = movies[['Movie_Title','Movie_Genre','Movie_Keywords','Movie_Tagline','Movie_Cast','Movie_Director']].fillna('')

Here, we selected 5 existing features to recommend movies.

In [ ]:
movies_features.shape

(4760, 6)

In [ ]:
movies_features

Movie_Title                       Movie_Genre  \
0                      Four Rooms                      Crime Comedy   
1                       Star Wars  Adventure Action Science Fiction   
2                    Finding Nemo                  Animation Family   
3                    Forrest Gump              Comedy Drama Romance   
4                 American Beauty                             Drama   
...                           ...                               ...   
4755             Midnight Cabaret                            Horror   
4756             Growing Up Smith               Comedy Family Drama   
4757                       8 Days                    Thriller Drama   
4758              Running Forever                            Family   
4759  To Be Frank, Sinatra at 100                       Documentary   

                                         Movie_Keywords  \
0             hotel new year's eve witch bet hotel room   
1           android galaxy hermit death star lightsaber   
2     father son relationship harbor underwater fish...   
3     vietnam veteran hippie mentally disabled runni...   
4     male nudity female nudity adultery midlife cri...   
...                                                 ...   
4755                                                      
4756                                                      
4757                     christian film sex trafficking   
4758                                                      
4759  music actors legendary perfomer classic hollyw...   

                                          Movie_Tagline  \
0     Twelve outrageous guests. Four scandalous requ...   
1          A long time ago in a galaxy far, far away...   
2     There are 3.7 trillion fish in the ocean, they...   
3     The world will never be the same, once you've ...   
4                                          Look closer.   
...                                                 ...   
4755                The hot spot where Satan's waitin'.   
4756           It’s better to stand out than to fit in.   
4757           She never knew it could happen to her...   
4758                                                      
4759                                                      

                                             Movie_Cast     Movie_Director  
0     Tim Roth Antonio Banderas Jennifer Beals Madon...     Allison Anders  
1     Mark Hamill Harrison Ford Carrie Fisher Peter ...       George Lucas  
2     Albert Brooks Ellen DeGeneres Alexander Gould ...     Andrew Stanton  
3     Tom Hanks Robin Wright Gary Sinise Mykelti Wil...    Robert Zemeckis  
4     Kevin Spacey Annette Bening Thora Birch Wes Be...         Sam Mendes  
...                                                 ...                ...  
4755  Lisa Hart Carroll Michael Des Barres Paul Drak...         Pece Dingo  
4756  Roni Akurati Brighton Sharbino Jason Lee Anjul...       Frank Lotito  
4757  Nicole Smolen Kim Baldwin Ariana Stephens Brys...       Jaco Booyens  
4758                                                                        
4759                                    Tony Oppedisano  Simon Napier-Bell  

[4760 rows x 6 columns]

In [ ]:
x = movies_features['Movie_Title']+' '+movies_features['Movie_Genre']+' '+movies_features['Movie_Keywords']+' '+movies_features['Movie_Tagline']+' '+movies_features['Movie_Cast']+' '+movies_features['Movie_Director']+' '

In [ ]:
x

0       Four Rooms Crime Comedy hotel new year's eve w...
1       Star Wars Adventure Action Science Fiction and...
2       Finding Nemo Animation Family father son relat...
3       Forrest Gump Comedy Drama Romance vietnam vete...
4       American Beauty Drama male nudity female nudit...
                              ...                        
4755    Midnight Cabaret Horror  The hot spot where Sa...
4756    Growing Up Smith Comedy Family Drama  It’s bet...
4757    8 Days Thriller Drama christian film sex traff...
4758                          Running Forever Family     
4759    To Be Frank, Sinatra at 100 Documentary music ...
Length: 4760, dtype: object

In [ ]:
x.shape

(4760,)

# **Get Feature Text Conversion to Tokens**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer(max_features = 4760,stop_words = 'english')
vector = count.fit_transform(x.values.astype('U')).toarray()

In [ ]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vector.shape

(4760, 4760)

In [ ]:
print(vector)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# **Get Similarity Score using Cosine Similarity**

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_score = cosine_similarity(vector)
similarity_score

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.10910895,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.10910895, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [ ]:
similarity_score.shape

(4760, 4760)

In [ ]:
em = list(enumerate(similarity_score[2]))
em

[(0, 0.0),
 (1, 0.0),
 (2, 0.9999999999999997),
 (3, 0.0),
 (4, 0.0),
 (5, 0.0),
 (6, 0.0),
 (7, 0.0),
 (8, 0.0),
 (9, 0.0),
 (10, 0.0),
 (11, 0.0),
 (12, 0.0),
 (13, 0.0),
 (14, 0.23145502494313788),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.0),
 (20, 0.0),
 (21, 0.0),
 (22, 0.03779644730092272),
 (23, 0.0),
 (24, 0.0),
 (25, 0.036369648372665396),
 (26, 0.07412493166611012),
 (27, 0.0),
 (28, 0.0),
 (29, 0.0),
 (30, 0.0),
 (31, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (36, 0.0),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0),
 (42, 0.0),
 (43, 0.0),
 (44, 0.0),
 (45, 0.036369648372665396),
 (46, 0.0),
 (47, 0.04335549847620599),
 (48, 0.0),
 (49, 0.03779644730092272),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.12964074471043285),
 (54, 0.0),
 (55, 0.0),
 (56, 0.0),
 (57, 0.0472455591261534),
 (58, 0.1336306209562122),
 (59, 0.0),
 (60, 0.0),
 (61, 0.034503277967117704),
 (62, 0.0),
 (63, 0.0),
 (64, 0.05698028822981897),
 (65, 0.0),
 (66, 0.0)

## **Get Movie Name as Input from user and validate for Closest Spelling**

In [ ]:
favourite_movie_name = input('Enter your favourite movie name: ')

Enter your favourite movie name: pirates of the carribeam


In [ ]:
all_movies_title_list = movies['Movie_Title'].tolist()

In [ ]:
import difflib

In [ ]:
movie_recommendation = difflib.get_close_matches(favourite_movie_name, all_movies_title_list)
print(movie_recommendation)

["Pirates of the Caribbean: At World's End", 'Rise of the Guardians', 'Battle of the Year']


In [ ]:
close_match = movie_recommendation[0]
close_match

"Pirates of the Caribbean: At World's End"

In [ ]:
index_of_close_match_movie = movies[movies.Movie_Title == close_match]['Movie_ID'].values[0]
print(index_of_close_match_movie)

131


In [ ]:
recommendation_score = list(enumerate(similarity_score[index_of_close_match_movie]))
print(recommendation_score)

[(0, 0.0), (1, 0.0), (2, 0.0), (3, 0.03984095364447979), (4, 0.0), (5, 0.0), (6, 0.042796049251091296), (7, 0.04652421051992354), (8, 0.0), (9, 0.0), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.04550157551932901), (14, 0.0), (15, 0.04052204492365539), (16, 0.0), (17, 0.042796049251091296), (18, 0.0), (19, 0.08728715609439697), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.04199605255658081), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.0), (30, 0.0), (31, 0.07597371763975865), (32, 0.04052204492365539), (33, 0.0), (34, 0.0), (35, 0.0), (36, 0.0), (37, 0.042796049251091296), (38, 0.044543540318737404), (39, 0.04052204492365539), (40, 0.0), (41, 0.0), (42, 0.0), (43, 0.0), (44, 0.08559209850218259), (45, 0.08399210511316162), (46, 0.0), (47, 0.0), (48, 0.0), (49, 0.0), (50, 0.04199605255658081), (51, 0.0), (52, 0.0), (53, 0.03742405942825598), (54, 0.0), (55, 0.0), (56, 0.0), (57, 0.0), (58, 0.0), (59, 0.0), (60, 0.0), (61, 0.03984095364447979), (62, 0.0), (63, 0.04123930494211612

In [ ]:
len(recommendation_score)

4760

# **Sorting the movies based on their similarity score**


In [ ]:
sorted_similar_movies = sorted(recommendation_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)
len(sorted_similar_movies)

[(131, 1.0000000000000002), (3252, 0.22750787759664506), (400, 0.20025046972870353), (2054, 0.19518001458970663), (1159, 0.18200630207731605), (881, 0.17118419700436519), (1961, 0.16798421022632323), (2203, 0.1649572197684645), (3706, 0.1649572197684645), (3205, 0.16448792373994225), (2942, 0.15430334996209194), (2844, 0.14754222271266348), (2625, 0.14638501094227996), (3570, 0.14285714285714288), (850, 0.13957263155977062), (2865, 0.13957263155977062), (3299, 0.13957263155977062), (3159, 0.13801311186847084), (1306, 0.1336306209562122), (2043, 0.1336306209562122), (232, 0.13093073414159545), (2226, 0.13093073414159545), (1425, 0.1283881477532739), (168, 0.12598815766974242), (2103, 0.12598815766974242), (3152, 0.12598815766974242), (3509, 0.12598815766974242), (1828, 0.12371791482634838), (2161, 0.12371791482634838), (3656, 0.12371791482634838), (1096, 0.12156613477096617), (1701, 0.12156613477096617), (3954, 0.12156613477096617), (3703, 0.12104550653376049), (3848, 0.1210455065337604

4760

In [ ]:
# print the name of similar movies based on the index
print("Movie title by your choice: ",favourite_movie_name)


print('Top 30 Movies suggested for you according to your favourite movie : \n')
i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies[movies.index==index]['Movie_Title'].values[0]
  if (i<31):
    print(i, '.',title_from_index)
    i+=1

Top 30 Movies suggested for you : 

1 . High Noon
2 . Trapeze
3 . A Man for All Seasons
4 . High Plains Drifter
5 . Pale Rider
6 . Hang 'em High
7 . Sky High
8 . Freddy Got Fingered
9 . One Man's Hero
10 . The Legend of the Lone Ranger
11 . The Nun's Story
12 . The Man from Snowy River
13 . Bronson
14 . Project X
15 . Seabiscuit
16 . April Fool's Day
17 . Julia
18 . Proud
19 . Chariots of Fire
20 . Renaissance Man
21 . Spider-Man 3
22 . The Children of Huang Shi
23 . Talladega Nights: The Ballad of Ricky Bobby
24 . A Fistful of Dollars
25 . Wyatt Earp
26 . Travellers and Magicians
27 . Prom
28 . Heaven's Gate
29 . Someone Like You...
30 . Extremely Loud & Incredibly Close
